name: Push To Kyso.io
on: [push]
jobs:
  Push-To-Kyso:
    runs-on: node:16.14.0-slim
    steps:
      - npm install -g kyso
      - kyso login --kysoInstallUrl https://kyso.io --provider kyso --username eduardo.suarez.guanes@gmail.com --token 824fb205-e725-4dbf-8e1f-a2a3a3b710fd
      - kyso push
